stages:
  - diff
  - deploy

image: quay.io/roboll/helmfile:helm3-v0.140.0

# TODO better workaround for environment limitation
# currently need it set for cluster access
# but jobs cannot have same environment

diff:
  stage: diff
  environment:
    name: space
  script:
    - helmfile repos
    - helmfile deps
    - helmfile lint 
    - helmfile diff

deploy:
  stage: deploy
  environment:
    name: space
  when: manual
  script:
    - helmfile apply

