stages:
  - diff
  - deploy

image: quay.io/roboll/helmfile:helm3-v0.140.0

variables:
 KUBE_CONTEXT: "treethought/spherics:spherics-agent"

.use_context: &use_context
  - kubectl config get-contexts
  - kubectl config use-context "$KUBE_CONTEXT"
  - kubectl get pods

diff:
  stage: diff
  script:
    - *use_context
    - helmfile repos
    - helmfile deps
    - helmfile lint 
    - helmfile diff

deploy:
  stage: deploy
  when: manual
  script:
    - *use_context
    - helmfile apply

