bases:
  - environments.yaml
---
repositories:
  - name: spherics
    url: https://charts.spherics.space

releases:
  # diaspora - Diaspora is a decentralized social network
  # https://diasporafoundation.org/
  # https://github.com/treethought/diaspora-helm

  - name: "diaspora"
    namespace: "diaspora"
    labels:
      chart: "diaspora"
      repo: "spherics"
      component: "diaspora"
      namespace: "diaspora"
      vendor: "spherics"
    chart: "spherics/diaspora"
    version: {{ .Values.chart_version | quote }}
    wait: true
    timeout: 300
    atomic: true
    cleanupOnFail: true
    createNamespace: true
    installed: {{ .Values.installed }}

    values:
      - host: {{ .Values.host }}
        postgresql:
          global:
            postgresql:
              postgresqlUsername: {{ .Values.db.username | quote }}
              postgresqlPassword: {{ .Values.db.password | quote }}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx # TODO refactor to helmfile defaults
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            kubernetes.io/tls-acme: "true"
          hosts:
            - host: {{ .Values.host | quote }}
              paths:
                - path: /
                  pathType: Prefix
          tls: 
          - secretName: {{ printf "%s-tls" .Values.host | quote }}
            hosts:
              - {{ .Values.host | quote }}

        redis:
          enabled: true
          usePassword: false
