bases:
  - environments.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # owncloud - ownCloud is an open-source file sync, share and content collaboration software
  # https://owncloud.com/docs-guides/
  # https://github.com/bitnami/charts/blob/master/bitnami/owncloud/README.md
  # https://github.com/bitnami/charts/blob/master/bitnami/owncloud/values.yaml

  - name: "owncloud"
    namespace: "owncloud"
    labels:
      chart: "owncloud"
      repo: "bitnami"
      component: "owncloud"
      namespace: "owncloud"
      vendor: "bitnami"
    chart: "bitnami/owncloud"
    version: {{ .Values.chart_version | quote }}
    wait: true
    timeout: 300
    atomic: true
    cleanupOnFail: true
    createNamespace: true
    installed: {{ .Values.installed }}

    values:
      - owncloudPassword: {{ .Values.user.password | quote }}
        owncloudEmail: {{ .Values.user.email | quote }}
        owncloudUsername: {{ .Values.user.username | quote }}
