bases:
  - environments.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # owncloud - ownCloud is an open-source file sync, share and content collaboration software
  # https://owncloud.com/docs-guides/
  # https://github.com/bitnami/charts/blob/master/bitnami/owncloud/README.md
  # https://github.com/bitnami/charts/blob/master/bitnami/owncloud/values.yaml

  - name: "owncloud"
    namespace: "owncloud"
    labels:
      chart: "owncloud"
      repo: "bitnami"
      component: "owncloud"
      namespace: "owncloud"
      vendor: "bitnami"
    chart: "bitnami/owncloud"
    version: {{ .Values.chart_version | quote }}
    wait: true
    timeout: 300
    atomic: true
    cleanupOnFail: true
    createNamespace: true
    installed: {{ .Values.installed }}

    values:
      - owncloudPassword: {{ .Values.user.password | quote }}
        owncloudEmail: {{ .Values.user.email | quote }}
        owncloudUsername: {{ .Values.user.username | quote }}
        owncloudHost: {{ .Values.host | quote }}
        ingress:
          enabled: true
          certManager: true
          hostname: {{ .Values.host | quote }}
          pathType: ImplementationSpecific
          annotations: 
            kubernetes.io/ingress.class: nginx
          tls: true
        metrics:
          enabled: false
        mariadb:
          enabled: true
          auth:
            rootPassword: {{ .Values.db.rootPassword | quote}}
            database: owncloud
            username: {{ .Values.db.username}}
            password: {{ .Values.db.password}}
          primary:
            persistence:
              enabled: true
