bases:
  - environments.yaml
---
repositories:
  - name: nextcloud
    url: https://nextcloud.github.io/helm/

releases:
  # nextcloud - Nextcloud is a suite of client-server software for creating and using file hosting services. 
  # https://nextcloud.com/
  # https://github.com/nextcloud/helm
  # https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml

  - name: "nextcloud"
    namespace: "nextcloud"
    labels:
      chart: "nextcloud"
      repo: "nextcloud"
      component: "nextcloud"
      namespace: "nextcloud"
      vendor: "nextcloud"
    chart: "nextcloud/nextcloud"
    version: {{ .Values.chart_version | quote }}
    wait: true
    timeout: 300
    atomic: true
    cleanupOnFail: true
    createNamespace: true
    installed: {{ .Values.installed }}

    values:
      - nextcloud:
          host: {{.Values.host | quote}}
          username: {{ .Values.user.username | quote }}
          passwrod: {{ .Values.user.password | quote }}

          # Extra config files created in /var/www/html/config/
          # ref: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
          # https overwrite needed for login redirect
          configs:
            proxy.config.php: |-
              <?php
              $CONFIG = array (
                'overwriteprotocol' => 'https',
              );

        cronjob:
          enabled: true

        persistence:
          # Nextcloud Data (/var/www/html)
          enabled: true

        internalDatabase:
          enabled: false

        externalDatabase:
          enabled: true
          type: postgresql
          # TODO template db host
          host: nextcloud-postgresql.nextcloud.svc.cluster.local
          user: {{ .Values.db.username }}
          password: {{ .Values.db.password }}
          database: nextcloud

        postgresql:
          enabled: true
          postgresqlUsername: {{ .Values.db.username | quote }}
          postgresqlPassword: {{ .Values.db.password | quote }}
          postgresqlDatabase: nextcloud
          persistence:
            enabled: true
            size: 50Gi

        redis:
          enabled: true
          usePassword: true
          password: {{ .Values.redis.password }}



        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/proxy-body-size: "4G"
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/server-snippet: |-
              server_tokens off;
              proxy_hide_header X-Powered-By;

              rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
              rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
              rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
              location = /.well-known/carddav {
                return 301 $scheme://$host/remote.php/dav;
              }
              location = /.well-known/caldav {
                return 301 $scheme://$host/remote.php/dav;
              }
              location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
              }
              location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
                deny all;
              }
              location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
                deny all;
              }
          tls:
            - secretName: {{ printf "%s-tls" .Values.host | quote }}
              hosts:
                - {{ .Values.host | quote }}
